[workspace]

members = ["aoc-2024/day-10", 
    "aoc-2024/day-11", 
    "aoc-2024/day-12", 
    "aoc-2024/day-17", 
    "aoc-2024/day-18",
    "aoc-2024/day-19",
    "aoc-2024/day-20", "side-projects/index-benchmark"]
resolver = "2"
