[package]
name = "trees"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "binary"
path = "src/main.rs"

[dependencies]
anyhow = { version = "1.0.94", features = ["backtrace"] }
generic-array = "1.2.0"
rayon = "1.10.0"
